version: "3.8"

services:
  db:
    image: postgres:16
    container_name: quests_tracker_db
    environment:
      POSTGRES_DB: quests_tracker
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: devpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
